### ISSUE TITLE
自己写addons如何避免重新replay出现重复数据，和引用的这段有没有关系

### ISSUE THREAD

**Issue by tinyhill666** [FIBOSIO/fibos-accounts#4]
https://github.com/FIBOSIO/fibos-accounts/blob/f535f8b8f990f17191dbbc00d4571309b889ed5a/lib/defs/fibos_accounts.js#L7

**Comment by WxSimon** [comment]
没有关系，如果使用了 fibos-tracker 的话，当不删除db的 `fibos_blocks` 数据时，之前同步过的数据不会再同步。

代码内部做了了当前数据库最新块和区块高度的对比。

**Comment by tinyhill666** [comment]
抱歉问一下， hasOne的语法有什么 作用？

**Comment by WxSimon** [comment]
hasOne 的作用是建立两张表的主键关联。[文档地址](https://fibjs.github.io/fib-app/zh/guide.html#%E6%89%A9%E5%B1%95%E5%AF%B9%E8%B1%A1%E8%AE%BF%E9%97%AE-api)

比如存在表A 表B 。

表A hasOne(B). 那么在 表 A 中会存在一个 b_id 的字段。该字段的含义是表明和 B 中某条记录进行关联。

基于这个特性，在使用 RESTFul Api 进行请求 或 graphql 进行请求时，可以直接取到关联数据。
